---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - batch.stock-operator.crodrigues.org
  resources:
  - stockquotes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.stock-operator.crodrigues.org
  resources:
  - stockquotes/finalizers
  verbs:
  - update
- apiGroups:
  - batch.stock-operator.crodrigues.org
  resources:
  - stockquotes/status
  verbs:
  - get
  - patch
  - update
