# This rule is not used by the project stock-k8s-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the batch.stock-operator.crodrigues.org.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: stock-k8s-operator
    app.kubernetes.io/managed-by: kustomize
  name: stockquote-editor-role
rules:
- apiGroups:
  - batch.stock-operator.crodrigues.org
  resources:
  - stockquotes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.stock-operator.crodrigues.org
  resources:
  - stockquotes/status
  verbs:
  - get
