# This rule is not used by the project stock-k8s-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over batch.stock-operator.crodrigues.org.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: stock-k8s-operator
    app.kubernetes.io/managed-by: kustomize
  name: stockquote-admin-role
rules:
- apiGroups:
  - batch.stock-operator.crodrigues.org
  resources:
  - stockquotes
  verbs:
  - '*'
- apiGroups:
  - batch.stock-operator.crodrigues.org
  resources:
  - stockquotes/status
  verbs:
  - get
