# This rule is not used by the project stock-k8s-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to batch.stock-operator.crodrigues.org resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: stock-k8s-operator
    app.kubernetes.io/managed-by: kustomize
  name: stockquote-viewer-role
rules:
- apiGroups:
  - batch.stock-operator.crodrigues.org
  resources:
  - stockquotes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch.stock-operator.crodrigues.org
  resources:
  - stockquotes/status
  verbs:
  - get
