apiVersion: batch.stock-operator.crodrigues.org/v1
kind: StockQuote
metadata:
  name: aapl-stock
spec:
  ticker: AAPL
  timeInterval: 5  # Update every 5 minutes
  secretRef:
    name: polygon-api-key
    namespace: stock-k8s-operator-system
    key: api-key 