name: Tests

on:
  push:
  pull_request:

jobs:
  test:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Install Ginkgo
        run: |
          GINKGO_VERSION=$(go list -m -f "{{ .Version }}" github.com/onsi/ginkgo/v2)
          go install github.com/onsi/ginkgo/v2/ginkgo@${GINKGO_VERSION}

      - name: Running Tests
        run: |
          go mod tidy
          make test
